#!/usr/bin/env python3
"""
Generate the site's brand assets — favicon set and social-preview (Open Graph)
image — from the self-hosted OFL fonts in assets/fonts/.

Everything here is drawn from scratch out of the site's own palette and type,
so the output carries no third-party image rights.

    pip install pillow fonttools brotli
    python make_brand_assets.py

Outputs:
    favicon.ico                 16/32/48 multi-size
    favicon.svg                 vector, the arch from brand_mark.py
    assets/icon-192.png         PWA / Android
    assets/icon-512.png         PWA / Android
    assets/apple-touch-icon.png 180x180, square (iOS masks it itself)
    assets/og-image.png         1200x630 link preview (WhatsApp, Telegram, X…)
"""

import pathlib
import tempfile

from fontTools.merge import Merger
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from PIL import Image, ImageDraw, ImageFont

import brand_mark

ROOT = pathlib.Path(__file__).parent
FONTS = ROOT / "assets" / "fonts"

# ── Palette (mirrors the tokens in assets/style.css) ──────────────────────────
GOLD = (181, 98, 30)
GOLD_DARK = (122, 62, 14)
CREAM = (250, 248, 243)
PARCHMENT_TOP = (248, 243, 232)
PARCHMENT_BOT = (242, 237, 228)
INK = (30, 27, 23)
INK_2 = (92, 80, 68)

TITLE = "הגניזה הקהירית"
SUBTITLE = "חלון אל החיים היהודיים בימי הביניים"
# Deliberately carries no document count. The corpus grows whenever CI
# rebuilds from the Princeton CSV, and this PNG is generated by hand — any
# number baked in here goes stale silently. The count belongs in og:description,
# which build.py regenerates on every deploy.
FOOTLINE = "מבית הכנסת בן עזרא בקהיר העתיקה"


def _static(woff2_name, weight):
    """Instantiate one weight of a variable woff2 as a temporary static TTF."""
    font = instancer.instantiateVariableFont(
        TTFont(FONTS / woff2_name), {"wght": weight}
    )
    font.flavor = None
    out = pathlib.Path(tempfile.mkdtemp()) / f"{woff2_name}-{weight}.ttf"
    font.save(out)
    return out


def _static_merged(slug, weight):
    """Hebrew + Latin subsets of one family, merged into a single static TTF.

    The self-hosted webfonts are split by unicode-range, so the Hebrew file
    alone has no digits or Latin letters — text like "35,924" would render as
    tofu. Pillow has no font fallback, so we merge the subsets up front.
    """
    parts = [_static(f"{slug}-{s}.woff2", weight) for s in ("hebrew", "latin")]
    out = pathlib.Path(tempfile.mkdtemp()) / f"{slug}-{weight}-merged.ttf"
    merged = Merger().merge([str(p) for p in parts])
    merged.save(out)
    return out


# ── Favicon ───────────────────────────────────────────────────────────────────
# The arch from brand_mark.py, in cream on the gold tile. Its 32-unit box is
# scaled into the 64-unit tile around the arch's centre (16, 15.5); the strokes
# are heavier than on the page, so the mark survives being shrunk to 16px.
TILE_SCALE = 1.65
TILE_SHIFT = (32 - 16 * TILE_SCALE, 32 - 15.5 * TILE_SCALE)
TILE_STROKE = {"outer": 2.4, "inner": 2.0}   # in brand_mark's 32-unit box


def _hex(rgb):
    return "#%02x%02x%02x" % rgb


def build_favicon_svg():
    paths = "".join(
        f'\n  <path d="{brand_mark.path_d(p)}" stroke-width="{TILE_STROKE[k]}"/>'
        for k, group in (("outer", brand_mark.OUTER), ("inner", brand_mark.INNER))
        for p in group
    )
    svg = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" '
        'role="img" aria-label="הגניזה הקהירית">\n'
        "  <title>הגניזה הקהירית</title>\n"
        f'  <rect width="64" height="64" rx="13" fill="{_hex(GOLD)}"/>\n'
        f'  <g transform="translate({TILE_SHIFT[0]:g} {TILE_SHIFT[1]:g}) scale({TILE_SCALE:g})" '
        f'fill="none" stroke="{_hex(CREAM)}" stroke-linecap="round" stroke-linejoin="round">'
        f"{paths}\n  </g>\n"
        "</svg>\n"
    )
    (ROOT / "favicon.svg").write_text(svg, encoding="utf-8")
    print("  ✓  favicon.svg")


def draw_mark(draw, origin, scale, colours, widths):
    """Draw the arch with Pillow: each path flattened to a polyline, with
    round joints and a disc on each end for the round caps."""
    ox, oy = origin
    for key, group in (("outer", brand_mark.OUTER), ("inner", brand_mark.INNER)):
        w = widths[key] * scale
        for path in group:
            pts = [(ox + x * scale, oy + y * scale) for x, y in brand_mark.polyline(path)]
            draw.line(pts, fill=colours[key], width=max(1, round(w)), joint="curve")
            for x, y in (pts[0], pts[-1]):
                draw.ellipse([x - w / 2, y - w / 2, x + w / 2, y + w / 2], fill=colours[key])


def build_favicon_pngs(supersample=10):
    """Render the same mark as bitmaps, each at its native size."""

    def tile(size, rounded=True):
        n = size * supersample
        img = Image.new("RGBA", (n, n), (0, 0, 0, 0))
        draw = ImageDraw.Draw(img)
        if rounded:
            draw.rounded_rectangle([0, 0, n - 1, n - 1], radius=int(n * 13 / 64), fill=GOLD)
        else:
            draw.rectangle([0, 0, n - 1, n - 1], fill=GOLD)
        unit = n / 64
        draw_mark(draw, (TILE_SHIFT[0] * unit, TILE_SHIFT[1] * unit), TILE_SCALE * unit,
                  {"outer": CREAM, "inner": CREAM}, TILE_STROKE)
        return img.resize((size, size), Image.LANCZOS)

    tile(512).save(ROOT / "assets" / "icon-512.png")
    tile(192).save(ROOT / "assets" / "icon-192.png")
    tile(180, rounded=False).save(ROOT / "assets" / "apple-touch-icon.png")

    frames = [tile(s) for s in (48, 32, 16)]
    frames[0].save(
        ROOT / "favicon.ico",
        format="ICO",
        sizes=[(48, 48), (32, 32), (16, 16)],
        append_images=frames[1:],
    )
    print("  ✓  favicon.ico, apple-touch-icon.png, icon-192.png, icon-512.png")


# ── Social preview ────────────────────────────────────────────────────────────
def build_og_image(heebo_bold, heebo_reg, heebo_med, width=1200, height=630):
    img = Image.new("RGB", (width, height), PARCHMENT_TOP)
    draw = ImageDraw.Draw(img, "RGBA")

    # Parchment wash, top to bottom
    for y in range(height):
        t = y / (height - 1)
        draw.line(
            [(0, y), (width, y)],
            fill=tuple(
                round(a + (b - a) * t) for a, b in zip(PARCHMENT_TOP, PARCHMENT_BOT)
            ),
        )

    # Faint manuscript ruling
    for y in range(120, height - 90, 46):
        draw.line([(70, y), (width - 70, y)], fill=GOLD + (12,), width=1)

    # Gold spine down the leading (right) edge, RTL
    draw.rectangle([width - 14, 0, width, height], fill=GOLD)

    right = width - 96          # text baseline edge (RTL: text grows leftwards)
    kw = dict(anchor="ra", direction="rtl", language="he")

    # The site mark (brand_mark.py), as over the title on the home page.
    # Drawn at 4x and scaled down, since Pillow does not antialias lines.
    ss, scale = 4, 2.7
    mark = Image.new("RGBA", (int(32 * scale * ss),) * 2, (0, 0, 0, 0))
    draw_mark(ImageDraw.Draw(mark), (0, 0), scale * ss,
              {"outer": GOLD, "inner": INK_2}, {"outer": 1.6, "inner": 1.3})
    mark = mark.resize((int(32 * scale),) * 2, Image.LANCZOS)
    img.paste(mark, (round(right - 16 * scale - 13), round(112 - 15.5 * scale)), mark)

    # Heebo, not Frank Ruhl Libre: .site-title and .site-subtitle both use
    # --font-ui, so the card has to match the page it represents.
    draw.text((right, 168), TITLE, font=ImageFont.truetype(str(heebo_bold), 104),
              fill=INK, **kw)

    draw.line([(right - 300, 316), (right, 316)], fill=GOLD, width=3)

    draw.text((right, 348), SUBTITLE, font=ImageFont.truetype(str(heebo_reg), 42),
              fill=INK_2, **kw)

    draw.text((right, 470), FOOTLINE, font=ImageFont.truetype(str(heebo_med), 31),
              fill=GOLD_DARK, **kw)

    draw.text((right, 540), "Princeton Geniza Project · CC BY-NC 4.0",
              font=ImageFont.truetype(str(heebo_reg), 23), fill=INK_2 + (170,),
              anchor="ra")

    out = ROOT / "assets" / "og-image.png"
    img.save(out, optimize=True)
    print(f"  ✓  assets/og-image.png ({out.stat().st_size // 1024} KB)")


def main():
    print("\n── Brand assets ──────────────────────────────────────")
    build_favicon_svg()
    build_favicon_pngs()
    build_og_image(
        _static_merged("heebo", 700),
        _static_merged("heebo", 400),
        _static_merged("heebo", 500),
    )
    print("── Done ──────────────────────────────────────────────\n")


if __name__ == "__main__":
    main()
