#!/usr/bin/env python3
"""
Generate the site's brand assets — favicon set and social-preview (Open Graph)
image — from the self-hosted OFL fonts in assets/fonts/.

Everything here is drawn from scratch out of the site's own palette and type,
so the output carries no third-party image rights.

    pip install pillow fonttools brotli
    python make_brand_assets.py

Outputs:
    favicon.ico                 16/32/48 multi-size
    favicon.svg                 vector, from the Frank Ruhl Libre gimel outline
    assets/icon-192.png         PWA / Android
    assets/icon-512.png         PWA / Android
    assets/apple-touch-icon.png 180x180, square (iOS masks it itself)
    assets/og-image.png         1200x630 link preview (WhatsApp, Telegram, X…)
"""

import pathlib
import tempfile

from fontTools.merge import Merger
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen
from PIL import Image, ImageDraw, ImageFont

ROOT = pathlib.Path(__file__).parent
FONTS = ROOT / "assets" / "fonts"

# ── Palette (mirrors the tokens in assets/style.css) ──────────────────────────
GOLD = (181, 98, 30)
GOLD_DARK = (122, 62, 14)
CREAM = (250, 248, 243)
PARCHMENT_TOP = (248, 243, 232)
PARCHMENT_BOT = (242, 237, 228)
INK = (30, 27, 23)
INK_2 = (92, 80, 68)

TITLE = "הגניזה הקהירית"
SUBTITLE = "חלון אל החיים היהודיים בימי הביניים"
# Deliberately carries no document count. The corpus grows whenever CI
# rebuilds from the Princeton CSV, and this PNG is generated by hand — any
# number baked in here goes stale silently. The count belongs in og:description,
# which build.py regenerates on every deploy.
FOOTLINE = "מבית הכנסת בן עזרא בקהיר העתיקה"


def _static(woff2_name, weight):
    """Instantiate one weight of a variable woff2 as a temporary static TTF."""
    font = instancer.instantiateVariableFont(
        TTFont(FONTS / woff2_name), {"wght": weight}
    )
    font.flavor = None
    out = pathlib.Path(tempfile.mkdtemp()) / f"{woff2_name}-{weight}.ttf"
    font.save(out)
    return out


def _static_merged(slug, weight):
    """Hebrew + Latin subsets of one family, merged into a single static TTF.

    The self-hosted webfonts are split by unicode-range, so the Hebrew file
    alone has no digits or Latin letters — text like "35,924" would render as
    tofu. Pillow has no font fallback, so we merge the subsets up front.
    """
    parts = [_static(f"{slug}-{s}.woff2", weight) for s in ("hebrew", "latin")]
    out = pathlib.Path(tempfile.mkdtemp()) / f"{slug}-{weight}-merged.ttf"
    merged = Merger().merge([str(p) for p in parts])
    merged.save(out)
    return out


# ── Favicon ───────────────────────────────────────────────────────────────────
def build_favicon_svg(frl_woff2="frank-ruhl-libre-hebrew.woff2"):
    """Trace the gimel (ג) outline into a dependency-free vector favicon."""
    font = instancer.instantiateVariableFont(TTFont(FONTS / frl_woff2), {"wght": 900})
    glyphs = font.getGlyphSet()
    name = font.getBestCmap()[ord("ג")]

    bounds = BoundsPen(glyphs)
    glyphs[name].draw(bounds)
    x0, y0, x1, y1 = bounds.bounds

    pen = SVGPathPen(glyphs)
    glyphs[name].draw(pen)

    target_h = 42.0
    scale = target_h / (y1 - y0)
    width = (x1 - x0) * scale
    tx = (64 - width) / 2 - x0 * scale
    ty = 32 + target_h / 2 - y0 * scale

    svg = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" '
        'role="img" aria-label="הגניזה הקהירית">\n'
        "  <title>הגניזה הקהירית</title>\n"
        f'  <rect width="64" height="64" rx="13" fill="#{GOLD[0]:02x}{GOLD[1]:02x}{GOLD[2]:02x}"/>\n'
        f'  <path transform="translate({tx:.3f} {ty:.3f}) scale({scale:.5f} -{scale:.5f})"'
        f' fill="#{CREAM[0]:02x}{CREAM[1]:02x}{CREAM[2]:02x}" d="{pen.getCommands()}"/>\n'
        "</svg>\n"
    )
    (ROOT / "favicon.svg").write_text(svg, encoding="utf-8")
    print("  ✓  favicon.svg")


def build_favicon_pngs(ttf, supersample=10, glyph_frac=0.66):
    """Render the same mark as bitmaps, each at its native size."""

    def tile(size, rounded=True):
        n = size * supersample
        img = Image.new("RGBA", (n, n), (0, 0, 0, 0))
        draw = ImageDraw.Draw(img)
        if rounded:
            draw.rounded_rectangle([0, 0, n - 1, n - 1], radius=int(n * 13 / 64), fill=GOLD)
        else:
            draw.rectangle([0, 0, n - 1, n - 1], fill=GOLD)

        target = n * glyph_frac
        size_px = int(target * 1.7)
        while size_px > 8:
            font = ImageFont.truetype(str(ttf), size_px)
            box = draw.textbbox((0, 0), "ג", font=font)
            if box[3] - box[1] <= target:
                break
            size_px = int(size_px * 0.95)

        box = draw.textbbox((0, 0), "ג", font=font)
        w, h = box[2] - box[0], box[3] - box[1]
        draw.text(((n - w) / 2 - box[0], (n - h) / 2 - box[1]), "ג", font=font, fill=CREAM)
        return img.resize((size, size), Image.LANCZOS)

    tile(512).save(ROOT / "assets" / "icon-512.png")
    tile(192).save(ROOT / "assets" / "icon-192.png")
    tile(180, rounded=False).save(ROOT / "assets" / "apple-touch-icon.png")

    frames = [tile(s) for s in (48, 32, 16)]
    frames[0].save(
        ROOT / "favicon.ico",
        format="ICO",
        sizes=[(48, 48), (32, 32), (16, 16)],
        append_images=frames[1:],
    )
    print("  ✓  favicon.ico, apple-touch-icon.png, icon-192.png, icon-512.png")


# ── Social preview ────────────────────────────────────────────────────────────
def build_og_image(heebo_bold, heebo_reg, heebo_med, width=1200, height=630):
    img = Image.new("RGB", (width, height), PARCHMENT_TOP)
    draw = ImageDraw.Draw(img, "RGBA")

    # Parchment wash, top to bottom
    for y in range(height):
        t = y / (height - 1)
        draw.line(
            [(0, y), (width, y)],
            fill=tuple(
                round(a + (b - a) * t) for a, b in zip(PARCHMENT_TOP, PARCHMENT_BOT)
            ),
        )

    # Faint manuscript ruling
    for y in range(120, height - 90, 46):
        draw.line([(70, y), (width - 70, y)], fill=GOLD + (12,), width=1)

    # Gold spine down the leading (right) edge, RTL
    draw.rectangle([width - 14, 0, width, height], fill=GOLD)

    right = width - 96          # text baseline edge (RTL: text grows leftwards)
    kw = dict(anchor="ra", direction="rtl", language="he")

    # Four-pointed star, echoing the ✦ in the site header (drawn, not typeset —
    # neither webfont carries U+2726).
    cx, cy, arm, waist = right - 13, 112, 26, 6
    draw.polygon(
        [(cx, cy - arm), (cx + waist, cy - waist), (cx + arm, cy),
         (cx + waist, cy + waist), (cx, cy + arm), (cx - waist, cy + waist),
         (cx - arm, cy), (cx - waist, cy - waist)],
        fill=GOLD + (205,),
    )

    # Heebo, not Frank Ruhl Libre: .site-title and .site-subtitle both use
    # --font-ui, so the card has to match the page it represents.
    draw.text((right, 168), TITLE, font=ImageFont.truetype(str(heebo_bold), 104),
              fill=INK, **kw)

    draw.line([(right - 300, 316), (right, 316)], fill=GOLD, width=3)

    draw.text((right, 348), SUBTITLE, font=ImageFont.truetype(str(heebo_reg), 42),
              fill=INK_2, **kw)

    draw.text((right, 470), FOOTLINE, font=ImageFont.truetype(str(heebo_med), 31),
              fill=GOLD_DARK, **kw)

    draw.text((right, 540), "Princeton Geniza Project · CC BY-NC 4.0",
              font=ImageFont.truetype(str(heebo_reg), 23), fill=INK_2 + (170,),
              anchor="ra")

    out = ROOT / "assets" / "og-image.png"
    img.save(out, optimize=True)
    print(f"  ✓  assets/og-image.png ({out.stat().st_size // 1024} KB)")


def main():
    print("\n── Brand assets ──────────────────────────────────────")
    build_favicon_svg()
    build_favicon_pngs(_static("frank-ruhl-libre-hebrew.woff2", 900))
    build_og_image(
        _static_merged("heebo", 700),
        _static_merged("heebo", 400),
        _static_merged("heebo", 500),
    )
    print("── Done ──────────────────────────────────────────────\n")


if __name__ == "__main__":
    main()
