#!/usr/bin/env node
/* ================================================================
   ביקורת נגישות אוטומטית לאתר סטטי.
   ================================================================

   הפעלה בריפו הזה:
     npm i -D playwright        (או שימוש בכרומיום שכבר מותקן)
     node scripts/a11y-audit.mjs --root .          # ברירת המחדל: DEFAULT_PAGES שלמטה
     node scripts/a11y-audit.mjs --root . --pages / /privacy/
     node scripts/a11y-audit.mjs --root . --chrome /path/to/chrome

   הקובץ הגיע מערכת israeli-web-compliance. השינוי היחיד מול המקור הוא
   רשימת דפי ברירת המחדל: הסריקה האוטומטית של תיקיות הייתה מוצאת את
   35,940 עמודי המסמכים שתחת d/ ומריצה על כל אחד מהם שש בדיקות. במקום
   זה נבדק מדגם קבוע — דף אחד מכל *תבנית* באתר, כי כל עמודי d/ נוצרים
   מאותה תבנית אחת.

   מה נבדק — ולמה דווקא זה:

   1. סריקת CSS ל-font-size ב-px.
      פקד גודל הטקסט פועל בשינוי font-size של השורש, ו-px מתעלם ממנו.
      אתר שחצי מהגיליונות שלו ב-px מקבל פקד שעובד בחצי מהדפים —
      וזה נראה כאילו הוא עובד, כי משהו כן גדל.

   2. מדידת הגדלה בפועל (getComputedStyle).
      לא מספיק לבדוק שהתכונה data-fs נקבעת. בדיקה כזו עוברת בהצלחה
      על אתר קפוא לגמרי. כאן נמדד הגודל לפני ואחרי.

   3. מטריצת פקדי הנגישות מול כל דף.
      כל פקד נבדק מול הערך המחושב שהוא אמור לשנות.

   4. גלישה אופקית ב-320px (קריטריון 1.4.10 — Reflow), כולל בשילוב
      טקסט מוגדל וריווח מוגדל. הגדלת טקסט היא מה ששובר פריסות.

   5. בדיקות מבנה: h1 יחיד, lang/dir, alt לתמונות, שם נגיש לכל כפתור,
      מזהים כפולים, קישורים שבורים.

   6. שגיאות קונסול בכל דף.

   קוד יציאה 1 אם נמצאה בעיה — מתאים ל-CI.
   ================================================================ */

import { chromium } from 'playwright';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';

/* ---------- ארגומנטים ---------- */
const argv = process.argv.slice(2);
const arg = (n, d) => { const i = argv.indexOf('--' + n); return i > -1 ? argv[i + 1] : d; };
const list = (n) => {
  const i = argv.indexOf('--' + n);
  if (i < 0) return null;
  const out = [];
  for (let j = i + 1; j < argv.length && !argv[j].startsWith('--'); j++) out.push(argv[j]);
  return out.length ? out : null;
};
const ROOT = path.resolve(arg('root', '.'));
const BASE_ARG = arg('base', null);
const CHROME = arg('chrome', process.env.CHROME_PATH || undefined);

/* ---------- גילוי דפים ---------- */
function discover(dir, prefix = '/') {
  const out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith('.') || e.name === 'node_modules') continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...discover(full, prefix + e.name + '/'));
    else if (e.name === 'index.html') out.push(prefix);
    else if (e.name.endsWith('.html')) out.push(prefix + e.name);
  }
  return out;
}
/* דף אחד מכל תבנית: הגלריה (INDEX_HTML), עמוד כתוב ביד, שני המסמכים
   המשפטיים, עמוד מסמך (DOC_PAGE) ושני עמודי מפתח (INDEX_PAGE — הראשון
   והשני נבדלים בקישורי הדפדוף). discover() נשאר בקובץ ואפשר לקרוא לו
   ידנית, אבל אינו ברירת המחדל כאן. */
// One page per template. /t/ and /t/<slug>/ are the tag directory and a tag hub;
// both are generated by prerender.py and both carry the accessibility menu.
const DEFAULT_PAGES = ['/', '/about.html', '/privacy/', '/accessibility/',
                       '/d/444.html', '/d/', '/d/index-2.html',
                       '/t/', '/t/fustat/']
  .filter(u => BASE_ARG || fs.existsSync(path.join(ROOT, u.endsWith('/') ? u + 'index.html' : u)));
const PAGES = list('pages') || (BASE_ARG ? ['/'] : DEFAULT_PAGES);

/* ---------- שרת סטטי ---------- */
const MIME = { '.html':'text/html;charset=utf-8', '.js':'text/javascript;charset=utf-8',
  '.mjs':'text/javascript;charset=utf-8', '.css':'text/css;charset=utf-8', '.json':'application/json',
  '.svg':'image/svg+xml', '.png':'image/png', '.jpg':'image/jpeg', '.jpeg':'image/jpeg',
  '.gif':'image/gif', '.webp':'image/webp', '.woff2':'font/woff2', '.woff':'font/woff',
  '.ico':'image/x-icon', '.xml':'application/xml', '.txt':'text/plain',
  '.webmanifest':'application/manifest+json' };
let srv = null, BASE = BASE_ARG;
if (!BASE) {
  srv = http.createServer((q, r) => {
    let p = decodeURIComponent(q.url.split('?')[0]);
    if (p.endsWith('/')) p += 'index.html';
    const f = path.join(ROOT, p);
    if (!f.startsWith(ROOT) || !fs.existsSync(f) || fs.statSync(f).isDirectory()) { r.writeHead(404); return r.end('404'); }
    r.writeHead(200, { 'content-type': MIME[path.extname(f)] || 'application/octet-stream' });
    r.end(fs.readFileSync(f));
  });
  await new Promise(r => srv.listen(0, r));
  BASE = 'http://localhost:' + srv.address().port;
}

/* ---------- 1. סריקת CSS סטטית ---------- */
function scanCss(dir, acc = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith('.') || e.name === 'node_modules') continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) scanCss(full, acc);
    else if (e.name.endsWith('.css')) {
      const rel = path.relative(ROOT, full);
      fs.readFileSync(full, 'utf8').split('\n').forEach((line, i) => {
        const m = line.match(/font-size\s*:\s*([0-9.]+)px/);
        if (!m) return;
        /* שלוש המדרגות של a11y.css הן ההגדרה עצמה, לא הפרה. */
        if (/^\s*html(\[data-fs)?/.test(line)) return;
        /* פתח מילוט מתועד: פקד שנועד להישאר יציב בכל המדרגות (סרגל
           בחירת הגודל עצמו, למשל) יסומן בהערה a11y-allow-px באותה
           שורה. עדיף חריג מוצהר על בדיקה שמתרגלים להתעלם ממנה. */
        if (/a11y-allow-px/.test(line)) return;
        acc.push({ file: rel, line: i + 1, px: m[1], text: line.trim().slice(0, 70) });
      });
    }
  }
  return acc;
}

const problems = [];
const say = (s = '') => console.log(s);
const head = (s) => { say(); say('━'.repeat(64)); say(s); say('━'.repeat(64)); };

head('1. גדלי גופן ב-px בגיליונות הסגנון');
const pxHits = BASE_ARG ? [] : scanCss(ROOT);
if (BASE_ARG) say('  (דילוג — נבדק רק במצב --root)');
else if (!pxHits.length) say('  ✓ אין. כל מידות הטקסט יחסיות.');
else {
  problems.push(`${pxHits.length} גדלי גופן ב-px`);
  say(`  ✗ ${pxHits.length} הצהרות שלא יגיבו לפקד גודל הטקסט:`);
  pxHits.slice(0, 25).forEach(h => say(`     ${h.file}:${h.line}  ${h.px}px  →  ${(h.px/16)}rem   ${h.text}`));
  if (pxHits.length > 25) say(`     ... ועוד ${pxHits.length - 25}`);
}

/* ---------- דפדפן ---------- */
const browser = await chromium.launch(CHROME ? { executablePath: CHROME } : {});
const newPage = async (w = 420, h = 900) => {
  const ctx = await browser.newContext({ viewport: { width: w, height: h } });
  const p = await ctx.newPage();
  p._errs = [];
  p.on('pageerror', e => p._errs.push('PAGEERROR: ' + e.message));
  p.on('console', m => { if (m.type() === 'error') p._errs.push('CONSOLE: ' + m.text()); });
  p._ctx = ctx;
  return p;
};
const openPage = async (url, w, h) => {
  const p = await newPage(w, h);
  await p.goto(BASE + url, { waitUntil: 'networkidle' });
  if (await p.locator('.consent-ok').count()) await p.click('.consent-ok');
  return p;
};

/* ---------- 2. הגדלה בפועל ---------- */
head('2. האם הטקסט באמת גדל (getComputedStyle)');
for (const url of PAGES) {
  const p = await openPage(url);
  const has = await p.evaluate(() =>
    (typeof A11Y !== 'undefined' && typeof A11Y.setFontSize === 'function') || typeof setFontSize === 'function');
  if (!has) { say(`  ${url}  —  אין רכיב נגישות בדף`); problems.push(`אין רכיב נגישות ב-${url}`); await p._ctx.close(); continue; }
  const measure = () => p.evaluate(() => {
    const out = [];
    const seen = new Set();
    document.querySelectorAll('h1,h2,h3,p,li,td,a,button,span').forEach(e => {
      if (!e.textContent.trim() || e.closest('.a11y-panel,.consent')) return;
      /* סרגל בחירת הגודל עצמו אינו אמור לגדול — הוא העוגן שמולו
         משווים. אותו חריג כמו a11y-allow-px ב-CSS; אפשר לסמן כל
         פקד אחר ב-data-a11y-allow-px.

         :not(:root) הוא העיקר כאן. a11y.js קובע data-fs על <html>
         עצמו — שם המדרגה נשמרת — ולכן closest('[data-fs]') מצא את
         השורש והחזיר true לכל אלמנט בדף. הבדיקה דיווחה "0 אלמנטים,
         כולם גדלים" על כל דף, כולל דף קפוא לחלוטין. */
      if (e.closest('[data-fs]:not(:root),[data-a11y-allow-px]')) return;
      const key = e.tagName + '|' + (e.className || '');
      if (seen.has(key) || seen.size > 40) return;
      seen.add(key);
      out.push({ key, size: parseFloat(getComputedStyle(e).fontSize) });
    });
    return out;
  });
  const before = await measure();
  await p.evaluate(() => {
    if (typeof A11Y !== 'undefined' && A11Y.setFontSize) A11Y.setFontSize('l');
    else setFontSize('l');
  });
  await p.waitForTimeout(120);
  const after = await measure();
  const map = Object.fromEntries(after.map(x => [x.key, x.size]));
  const frozen = before.filter(x => map[x.key] && map[x.key] / x.size < 1.2);
  if (!frozen.length) say(`  ✓ ${url}  —  ${before.length} אלמנטים, כולם גדלים`);
  else {
    problems.push(`${frozen.length} אלמנטים קפואים ב-${url}`);
    say(`  ✗ ${url}  —  ${frozen.length} מתוך ${before.length} קפואים:`);
    frozen.slice(0, 8).forEach(f => say(`     ${f.key}  ${f.size}px → ${map[f.key]}px`));
  }
  await p._ctx.close();
}

/* ---------- 3. מטריצת הפקדים ---------- */
head('3. מטריצת פקדי הנגישות');
const CHECKS = {
  'ניגודיות גבוהה': async p => { await p.click('[data-mode="contrast"]'); await p.waitForTimeout(80);
    const r = await p.evaluate(() => getComputedStyle(document.body).color); await p.click('[data-mode="contrast"]');
    return r === 'rgb(0, 0, 0)'; },
  'ניגודיות הפוכה': async p => { await p.click('[data-mode="invert"]'); await p.waitForTimeout(80);
    const r = await p.evaluate(() => getComputedStyle(document.body).backgroundColor); await p.click('[data-mode="invert"]');
    return r === 'rgb(0, 0, 0)'; },
  /* שתי דרכים לגיטימיות ליישם גווני אפור: filter על התוכן, או דריסת
     משתני הצבע (נקי יותר). הבדיקה מודדת את התוצאה — האם צבע רווי
     כלשהו בדף חדל להיות רווי — ולא את המימוש. */
  'גווני אפור': async p => {
    const sat = () => p.evaluate(() => {
      const rgb = c => (c.match(/[\d.]+/g) || []).slice(0, 3).map(Number);
      let max = 0;
      document.querySelectorAll('body *:not(.a11y-panel):not(.a11y-panel *)').forEach(e => {
        const cs = getComputedStyle(e);
        for (const v of [cs.color, cs.backgroundColor, cs.borderTopColor]) {
          const c = rgb(v); if (c.length < 3) continue;
          max = Math.max(max, Math.max(...c) - Math.min(...c));
        }
      });
      return max;   /* 0 = אפור מוחלט */
    });
    const before = await sat();
    await p.click('[data-mode="mono"]'); await p.waitForTimeout(120);
    const after = await sat();
    const filtered = await p.evaluate(() =>
      [...document.body.children].some(e => getComputedStyle(e).filter.includes('grayscale')));
    await p.click('[data-mode="mono"]');
    /* דף שכמעט אין בו צבע מלכתחילה אינו יכול "להפוך לאפור" בצורה
       מדידה — אין מה להוריד. במקרה כזה אין ממצא. */
    return filtered || before < 40 || after < before * 0.5;
  },
  'פונט קריא': async p => { await p.click('[data-flag="readable"]'); await p.waitForTimeout(80);
    const r = await p.evaluate(() => getComputedStyle(document.body).fontFamily.includes('Arial')); await p.click('[data-flag="readable"]');
    return r; },
  'ריווח מוגדל': async p => { await p.click('[data-flag="spacing"]'); await p.waitForTimeout(80);
    const r = await p.evaluate(() => getComputedStyle(document.body).letterSpacing !== 'normal'); await p.click('[data-flag="spacing"]');
    return r; },
  'הדגשת קישורים': async p => { await p.click('[data-flag="links"]'); await p.waitForTimeout(80);
    const r = await p.evaluate(() => { const a = document.querySelector('a[href]'); return a ? getComputedStyle(a).textDecorationThickness === '2px' : true; });
    await p.click('[data-flag="links"]'); return r; },
  'הדגשת מיקוד': async p => { await p.click('[data-flag="focus"]'); await p.waitForTimeout(80);
    const r = await p.evaluate(() => { const f = document.querySelector('.a11y-fab'); f.focus(); return parseFloat(getComputedStyle(f).outlineWidth) >= 4; });
    await p.click('[data-flag="focus"]'); return r; },
  'סמן גדול': async p => { await p.click('[data-flag="cursor"]'); await p.waitForTimeout(80);
    const r = await p.evaluate(() => getComputedStyle(document.body).cursor.includes('data:image')); await p.click('[data-flag="cursor"]');
    return r; },
  'עצירת אנימציות': async p => { await p.click('[data-flag="still"]'); await p.waitForTimeout(80);
    const r = await p.evaluate(() => getComputedStyle(document.querySelector('.a11y-fab')).transitionDuration === '0s'); await p.click('[data-flag="still"]');
    return r; },
};
const names = Object.keys(CHECKS);
const grid = {};
for (const url of PAGES) {
  const p = await openPage(url);
  if (!(await p.locator('.a11y-fab').count())) { await p._ctx.close(); continue; }
  await p.click('.a11y-fab');
  grid[url] = {};
  for (const n of names) { try { grid[url][n] = await CHECKS[n](p); } catch (e) { grid[url][n] = false; } }
  await p._ctx.close();
}
const cols = Object.keys(grid);
if (!cols.length) say('  אין דף עם רכיב נגישות.');
else {
  const w = Math.max(...names.map(n => n.length)) + 2;
  say(' '.repeat(w) + cols.map(c => c.slice(0, 13).padStart(15)).join(''));
  for (const n of names) {
    let line = n.padEnd(w);
    for (const c of cols) { const v = grid[c][n]; if (!v) problems.push(`${n} לא פועל ב-${c}`); line += (v ? '✓' : '✗').padStart(15); }
    say(line);
  }
}

/* ---------- 4. גלישה אופקית ---------- */
head('4. גלישה אופקית (1.4.10) — 320px ו-420px, שלושה מצבים');
let overflows = 0;
for (const w of [320, 420]) {
  for (const url of PAGES) {
    const p = await openPage(url, w, 800);
    for (const mode of ['רגיל', 'טקסט גדול', 'טקסט גדול + ריווח']) {
      await p.evaluate(m => {
        const big = m !== 'רגיל';
        const set = (typeof A11Y !== 'undefined' && A11Y.setFontSize) ? A11Y.setFontSize
                  : (typeof setFontSize === 'function' ? setFontSize : null);
        if (set) set(big ? 'l' : 's');
        document.documentElement.classList.toggle('a11y-spacing', m.includes('ריווח'));
      }, mode);
      await p.waitForTimeout(120);
      const r = await p.evaluate(() => ({ scroll: document.documentElement.scrollWidth, vw: document.documentElement.clientWidth }));
      if (r.scroll > r.vw + 1) { overflows++; problems.push(`גלישה ב-${url} ${w}px`);
        say(`  ✗ ${w}px ${url} [${mode}]  scrollWidth=${r.scroll} > ${r.vw}`); }
    }
    await p._ctx.close();
  }
}
if (!overflows) say('  ✓ אין גלישה אופקית באף דף, באף רוחב, באף מצב.');

/* ---------- 5. מבנה ---------- */
head('5. מבנה סמנטי, תוויות וקישורים');
for (const url of PAGES) {
  const p = await openPage(url);
  const info = await p.evaluate(() => ({
    h1: document.querySelectorAll('h1').length,
    lang: document.documentElement.lang,
    dir: document.documentElement.dir,
    noAlt: [...document.querySelectorAll('img')].filter(i => !i.hasAttribute('alt')).length,
    noName: [...document.querySelectorAll('button,a[href]')].filter(b =>
      !(b.innerText || '').trim() && !b.getAttribute('aria-label') && !b.getAttribute('title')).length,
    dup: (() => { const ids = [...document.querySelectorAll('[id]')].map(e => e.id); return [...new Set(ids.filter((v,i) => ids.indexOf(v) !== i))]; })(),
    rel: [...document.querySelectorAll('a[href]')].map(a => a.getAttribute('href')).filter(h => h && !/^(https?:|mailto:|tel:|#)/.test(h)),
  }));
  const bad = [];
  if (info.h1 !== 1) bad.push(`h1 count=${info.h1}`);
  if (!info.lang) bad.push('אין lang');
  if (info.noAlt) bad.push(`${info.noAlt} תמונות בלי alt`);
  if (info.noName) bad.push(`${info.noName} פקדים בלי שם נגיש`);
  if (info.dup.length) bad.push(`מזהים כפולים: ${info.dup.join(',')}`);
  if (!BASE_ARG) for (const h of new Set(info.rel)) {
    const t = new URL(h, BASE + url).pathname;
    if (!fs.existsSync(path.join(ROOT, t.endsWith('/') ? t + 'index.html' : t))) bad.push(`קישור שבור: ${h}`);
  }
  if (p._errs.length) bad.push(`שגיאות JS: ${p._errs.join(' | ').slice(0, 120)}`);
  if (bad.length) { problems.push(`מבנה ב-${url}`); say(`  ✗ ${url}\n     ${bad.join('\n     ')}`); }
  else say(`  ✓ ${url}`);
  await p._ctx.close();
}

/* ---------- 6. ניגודיות בפועל ---------- */
head('6. ניגודיות טקסט מול הרקע האפקטיבי (1.4.3)');
/* נבדק גם במצב "ניגודיות הפוכה", ולא רק במצב הרגיל: קישור שאף כלל
   CSS לא צבע מקבל את ברירת המחדל של הדפדפן (#0000EE), שנראית תקינה
   על רקע בהיר ונותנת 2.2:1 על שחור — כלומר נשברת בדיוק במצב שמשתמש
   לקוי ראייה מדליק. בדיקה במצב הרגיל בלבד לא תתפוס את זה. */
let lowCount = 0;
for (const url of PAGES) {
 for (const mode of ['רגיל', 'ניגודיות הפוכה']) {
  const p = await openPage(url);
  if (mode !== 'רגיל') {
    if (!(await p.locator('[data-mode="invert"]').count())) { await p._ctx.close(); continue; }
    await p.click('.a11y-fab'); await p.click('[data-mode="invert"]');
    await p.keyboard.press('Escape'); await p.waitForTimeout(120);
  }
  const low = await p.evaluate(() => {
    const toRgb = c => { const m = c.match(/[\d.]+/g); return m ? m.slice(0,3).map(Number) : null; };
    const lum = ([r,g,b]) => { const f = v => (v/=255) <= .03928 ? v/12.92 : ((v+.055)/1.055)**2.4;
      return .2126*f(r) + .7152*f(g) + .0722*f(b); };
    const ratio = (a,b) => { const [x,y] = [lum(a), lum(b)].sort((m,n)=>n-m); return (x+.05)/(y+.05); };
    /* הרקע האפקטיבי הוא של האב הראשון שאינו שקוף. */
    const bgOf = el => { let e = el;
      while (e) { const c = toRgb(getComputedStyle(e).backgroundColor);
        const a = getComputedStyle(e).backgroundColor.match(/[\d.]+/g);
        if (c && !(a && a.length === 4 && +a[3] === 0)) return c;
        e = e.parentElement; }
      return [255,255,255]; };
    const out = [], seen = new Set();
    document.querySelectorAll('body *').forEach(el => {
      if (el.closest('.a11y-panel, .consent, .a11y-fab')) return;
      const txt = [...el.childNodes].some(n => n.nodeType === 3 && n.textContent.trim());
      if (!txt) return;
      const cs = getComputedStyle(el);
      if (cs.visibility === 'hidden' || cs.display === 'none' || +cs.opacity === 0) return;
      const size = parseFloat(cs.fontSize);
      const bold = +cs.fontWeight >= 700;
      /* טקסט גדול (24px, או 18.66px מודגש) מסתפק ב-3:1 */
      const need = (size >= 24 || (size >= 18.66 && bold)) ? 3 : 4.5;
      const fg = toRgb(cs.color); if (!fg) return;
      const r = ratio(fg, bgOf(el));
      if (r >= need) return;
      const key = el.tagName + '.' + (el.className || '');
      if (seen.has(key)) return; seen.add(key);
      out.push({ key, r: +r.toFixed(2), need, size, color: cs.color,
                 sample: (el.textContent || '').trim().slice(0, 28) });
    });
    return out;
  });
  if (!low.length) say(`  ✓ ${url} [${mode}]`);
  else { lowCount += low.length; problems.push(`${low.length} כשלי ניגודיות ב-${url} [${mode}]`);
    say(`  ✗ ${url} [${mode}] — ${low.length} אלמנטים מתחת לסף:`);
    low.slice(0, 8).forEach(l => say(`     ${l.r}:1 (נדרש ${l.need}) ${l.key} ${l.size}px ${l.color}  "${l.sample}"`));
  }
  await p._ctx.close();
 }
}
if (!lowCount) say('  הרץ גם scripts/contrast.py על הפלטה — הוא מציע גוון חלופי לכל כשל.');

/* ---------- סיכום ---------- */
head(problems.length ? `נמצאו ${problems.length} בעיות` : 'הכול תקין');
problems.forEach(p => say('  · ' + p));
await browser.close();
if (srv) srv.close();
process.exit(problems.length ? 1 : 0);
